### ISSUE TITLE
migrating wallet issue

### ISSUE THREAD

**Issue by jacek111p** [ReeCore/Reex#2]
My old walet version is: v1.1.0.0-60025

New one I have installed is: recore 1.2
https://github.com/Hser2bio/Reex/releases/tag/2.2

When I look at description:

- delete all files in C:\Users\YOURWINDOWSUSER\AppData\Roaming\Reecore\ except the following files: wallet.dat / masternodes.conf /Reecore.conf

- I have no such old files. Only file I have is:
wallet.dat

I have installed new wallet on another location, but there I have no old coins from old wallet.

Please help
thanks

**Comment by Hser2bio** [comment]
Hi! you need follow instructions, you could not install in other location. need install in the same location. 

that is a update of wallet, so need the old wallet.dat

**Comment by jacek111p** [comment]
hi

As I wrote before - I can not follow instructions.
Look at it again:

- make a secure copy of your wallet.dat ( we suggest to external usb)
- delete all files in C:\Users\YOURWINDOWSUSER\AppData\Roaming\Reecore\ except the following files: wallet.dat / masternodes.conf /Reecore.conf
- execute new wallet: 

so I can not delete file masternodes.conf /Reecore.conf as there are not such there iside, so can not go to next step:
- execute new wallet: 

thanks
Jacek

**Comment by Hser2bio** [comment]
Hi again!

if you dont have reecore.conf neither masternode.conf your old installation is not fine. 

anyway, if you made a secure copy of your wallet.dat in other place, you could execute now the new wallet. 

when you run the new wallet could be 2 things:

1. you have the old balance, so you make the steps fine. 
2. you dont have the old balance. in this case:
    2.1 first let full sync the wallet. if still 0 in balance, need make 2.2.
    2.2 close QT, and replace the wallet.dat of folder by original copy of your wallet.dat

**Comment by jacek111p** [comment]
Hi

Unfortunatelly this did not fix my issue.
After I copiet wallet.dat and run app again I get:

Warning: error reading wallet.dat! All keys read correctly, but transaction data or address book entries might be missing or incorrect.

After it starts app with 0 balance Reex.

Please provide another solution.

thanks

**Comment by Hser2bio** [comment]
open wallet: tools: fix wallet: -zapwallettxets=2 and let work

that is due you had some problem in your file wallet.dat is not problem of wallet or swap.

**Comment by jacek111p** [comment]
Hi

I have done this and error disappeared, but after that I have still balance 0 Ree,

I have tested also all other fix wallet options but it did not help.

Please provide other solution to migrate my old wallet balance where I can see my balance and synchronizing with network is 2 weeks behind and not moving.

thanks

**Comment by Hser2bio** [comment]
1. if you see your old balance and dont sync is due this wallet is the OLD!
2. Understand that you are with 2 diferent pcs
3. need close both of them and move the wallet.dat that you have in old wallet to new wallet. mean, need copy file wallet.dat from pc that dont sync to the other pc that balance is 0

all of that, is due you still dont follow instructions.

**Comment by jacek111p** [comment]
hi

Ok, I have done this again accourding to your instructions.

I have RAR ed installed applications in 
C:\Users\YOURWINDOWSUSER\AppData\Roaming\Reecore\

just copied wallet.dat from old wallet, next I have installed again new ReeCore on default folder, moved old wallet.dat there.

When I opened it I got error like before so I used tools and fix wallet first for -zapwallettxets=2
later every other option.

Error disapeared, but after all I still have balance 0 REE.

Please provide other solution.

thanks

**Comment by jacek111p** [comment]
after I rar ed old applications, I have deleted it completly before installing again new ReeCore.

**Comment by jacek111p** [comment]
Hi

Did you create any new fixed reecore wallet?
My issue persists.

thanks

**Comment by Hser2bio** [comment]
the reecore wallet working fine, dont need no one fix. 

if you have problem, is in yourside, review all stepts. 

if you have 0 reecore is due you made some fail.

thanks

**Comment by jacek111p** [comment]
hi

Looks to me like this is al big cheat. 
I had Ree Core before, I spent money on this, exported wallet but now all is lost.
I have wallet on my PC I can delete it. 
Nobody helped me in any migration or anything.

This Ree Core is one big crap.
